version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - SKIP_PREFLIGHT_CHECK=true
      - CHOKIDAR_USEPOLLING=true